site_name: Codecheck Documentation
theme: readthedocs

# Choices remaining: readthedocs, yeti, journal
# readable, cosmo, flatly, spacelab, cerulean, slate, mkdocs, journal = not elegantly responsive
# cyborg, united, amelia, mkdocs =  does not match codecheck color scheme
# simplex = does not match codecheck font
# bootstrap = oh my god this bootstrap implementation is blegghghghghh

pages:
- はじめに: index_ja.md
- Webエディタの使用方法: guide_web_editor_ja.md
- Githubの使用方法: guide_github_ja.md
- チャレンジの運営: guide_organizing_challenges_ja.md
- リファレンス: reference_ja.md
